user = User.create(name: "Cristian",email: "user1@test.com",password_digest: "password",image_url: "https://avatar.iran.liara.run/public/1")
user = User.create(name: "Bob",email: "user2@test.com",password_digest: "password",image_url: "https://avatar.iran.liara.run/public/42")
user = User.create(name: "Charles",email: "user3@test.com",password_digest: "password",image_url: "https://robohash.org/stefan-one")
user = User.create(name: "Kelly",email: "user4@test.com",password_digest: "password",image_url: "https://avatar.iran.liara.run/public/92")
user = User.create(name: "John",email: "user5@test.com",password_digest: "password",image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJrctddrp7uic_Wrea3P8i7OsB_--o7hX7GQ&usqp=CAU")

exercise = Exercise.create(name: "bench press", description: "It involves lying on a bench and pressing weight upward using either a barbell or a pair of dumbbells.", image_url: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif", video_url: "https://youtu.be/SCVCLChPQFY")
exercise = Exercise.create(name: "shoulder press", description: "an upper-body weight training exercise in which the trainee presses a weight overhead while seated or standing", image_url: "https://static.strengthlevel.com/images/illustrations/dumbbell-shoulder-press-1000x1000.jpg", video_url: "https://youtu.be/5yWaNOvgFCM")
exercise = Exercise.create(name: "bicep curl", description: "Bicep curls are the classic go-to exercise for targeting the biceps brachii, the two-headed muscle responsible for flexing the elbow joint. This exercise involves gripping the dumbbells with an underhand (supine) grip, palms facing upward, and curling the weights towards your shoulders while keeping your elbows stationary.", image_url: "https://cdn.shopify.com/s/files/1/2384/0833/files/inner-bicep-curl-benefits.jpg?v=1689192787", video_url: "https://youtu.be/3OZ2MT_5r3Q")
exercise = Exercise.create(name: "back squat", description: "The back squat is a basic barbell strength exercise for the lower body with an emphasis on the quads, hamstrings, and glutes.", image_url: "https://www.muscleandfitness.com/wp-content/uploads/2014/02/116_B.jpg?quality=86&strip=all", video_url: "https://youtu.be/ultWZbUMPL8?si=jdY_hWdrnw1FY6PP")
exercise = Exercise.create(name: "barbell row", description: "Without moving your torso, bend your elbows and pull the bar to your upper abs. Squeeze your shoulder blades toward each other.", image_url: "https://hips.hearstapps.com/hmg-prod/images/workouts/2016/03/barbellrow-1457038583.gif?crop=1xw:0.75xh;center,top&resize=1200:*", video_url: "https://youtu.be/pNzp064j8g0?si=58TSbrBSuahL6lB4")

muscle_group = MuscleGroup.create(name: "Arms")
muscle_group = MuscleGroup.create(name: "Legs")
muscle_group = MuscleGroup.create(name: "Chest")
muscle_group = MuscleGroup.create(name: "Back")
muscle_group = MuscleGroup.create(name: "Shoulder")

routine = Routine.create(user_id: 1,	exercise_id: 1,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 1,	exercise_id: 2,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 1,	exercise_id: 3,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 1,	exercise_id: 4,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 1,	exercise_id: 5,	sets: 3,	reps: 8)

routine = Routine.create(user_id: 2,	exercise_id: 1,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 2,	exercise_id: 2,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 2,	exercise_id: 3,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 2,	exercise_id: 4,	sets: 3,	reps: 8)
routine = Routine.create(user_id: 2,	exercise_id: 5,	sets: 3,	reps: 8)

used_muscle = UsedMuscle.create(muscle_group_id: 3,exercise_id: 1)
used_muscle = UsedMuscle.create(muscle_group_id: 4,exercise_id: 1)
used_muscle = UsedMuscle.create(muscle_group_id: 5,exercise_id: 1)
used_muscle = UsedMuscle.create(muscle_group_id: 4,exercise_id: 2)
used_muscle = UsedMuscle.create(muscle_group_id: 5,exercise_id: 2)
used_muscle = UsedMuscle.create(muscle_group_id: 4,exercise_id: 3)
used_muscle = UsedMuscle.create(muscle_group_id: 1,exercise_id: 4)
used_muscle = UsedMuscle.create(muscle_group_id: 2,exercise_id: 5)
used_muscle = UsedMuscle.create(muscle_group_id: 4,exercise_id: 5)
used_muscle = UsedMuscle.create(muscle_group_id: 5,exercise_id: 5)
